name: zowe_flutter
description: A Flutter application that connects to z/OS via Zowe and z/OSMF.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  get_it: ^3.0.3
  provider: ^3.1.0+1
  logger: ^0.7.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - zowe.png
    - job.png
    - data_set.png